apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emqx-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: emqx
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metricName: emqx_connections
        targetValue: 1000
