apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emqx-hpa
  namespace: emqx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: emqx

  minReplicas: 1
  maxReplicas: 7

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1            # scale up 1 pod at a time
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100          
          periodSeconds: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20   # target CPU utilization
