apiVersion: v1
kind: Namespace
metadata:
  name: emqx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: emqx
  labels:
    app: emqx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:5.8.8
        ports:
        - name: mqtt
          containerPort: 1883
        - name: mqttssl
          containerPort: 8883
        - name: ws
          containerPort: 8083
        - name: wss
          containerPort: 8084
        - name: dashboard
          containerPort: 18083
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
  labels:
    app: emqx
spec:
  type: ClusterIP
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: mqttssl
    port: 8883
    targetPort: 8883
  - name: ws
    port: 8083
    targetPort: 8083
  - name: wss
    port: 8084
    targetPort: 8084
  - name: dashboard
    port: 18083
    targetPort: 18083
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emqx-hpa
  namespace: emqx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emqx
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
