apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emqx-hpa
  namespace: emqx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emqx
  minReplicas: 3   # Always start with 3
  maxReplicas: 7   # Always odd numbers
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 0
        periodSeconds: 300
