apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: emqx
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: emqx
  namespaceSelector:
    matchNames:
      - emqx-new
  endpoints:
    - port: metrics
      interval: 30s
