apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: emqx
  labels:
    app: emqx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:5.8.8
        ports:
        - containerPort: 1883   # MQTT
        - containerPort: 8883   # MQTT SSL
        - containerPort: 8083   # Websocket
        - containerPort: 8084   # Websocket SSL
        - containerPort: 18083  # Dashboard
        - containerPort: 4369   # Erlang distribution
        - containerPort: 25672  # Erlang distribution
        env:
        - name: EMQX_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EMQX_CLUSTER__DISCOVERY
          value: "k8s"       # Use Kubernetes-based auto-discovery
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: "emqx"
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: "https://kubernetes.default.svc:443"
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: "emqx"
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
  labels:
    app: emqx
spec:
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: mqttssl
    port: 8883
    targetPort: 8883
  - name: ws
    port: 8083
    targetPort: 8083
  - name: wss
    port: 8084
    targetPort: 8084
  - name: dashboard
    port: 18083
    targetPort: 18083
  type: ClusterIP
