apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emqx-connection-hpa
  namespace: emqx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: emqx
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: emqx_connections
      target:
        type: Value
        value: "500"   # scale when total connections > 500
